services:
  - type: web
    name: goatlab-ranking-api
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./Dockerfile.api
    healthCheckPath: /api/v1/health
    autoDeployTrigger: off
