"""Typed project-owned schemas."""

from goatlab.schemas.canonical import (
    AwardScope,
    AwardTaxonomyStatus,
    AwardType,
    CoverageStatus,
    FinalsGame,
    Franchise,
    Game,
    MetricCoverage,
    MetricOrigin,
    Player,
    PlayerAward,
    PlayerGameStats,
    PlayerSeasonAdvanced,
    PlayerSeasonStats,
    PlayerTeamSeasonParticipation,
    PostseasonFormatStatus,
    Season,
    SeasonRowScope,
    SeasonType,
    Team,
    TeamSeasonResult,
)

__all__ = [
    "AwardScope",
    "AwardTaxonomyStatus",
    "AwardType",
    "CoverageStatus",
    "FinalsGame",
    "Franchise",
    "Game",
    "MetricCoverage",
    "MetricOrigin",
    "Player",
    "PlayerAward",
    "PlayerGameStats",
    "PlayerSeasonAdvanced",
    "PlayerSeasonStats",
    "PlayerTeamSeasonParticipation",
    "PostseasonFormatStatus",
    "Season",
    "SeasonRowScope",
    "SeasonType",
    "Team",
    "TeamSeasonResult",
]
